name: Build Pull Request

on:
  pull_request:
    branches:
      - develop
      - release/*
      - support/*

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Build with Sonarcloud
        env:
          OPENSSL_CONF: /dev/null # Disable OpenSSL config to let phantomjs start, see https://stackoverflow.com/a/72679175
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B -ntp verify sonar:sonar
