name: Build Pull Request

on:
  pull_request:
    branches:
      - develop
      - release/*
      - support/*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Keeper-Security/ksm-action@v1
        if: ${{ env.KSM_CONFIG != '' }}
        env:
          KSM_CONFIG: ${{ secrets.KSM_CONFIG }}
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            ${{ vars.KEEPER_SONARCLOUD_RECORD_ID }}/field/password > env:SONAR_TOKEN

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build with Sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.SONAR_TOKEN != '' }}
        run: ./mvnw -B -ntp verify sonar:sonar
        
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.SONAR_TOKEN == '' }}
        run: ./mvnw -B -ntp verify
